# uncomment below and replace with your Project ID
# application: YOUR_PROJECT_ID
module: tictactoe
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: chatactoe.application
  #script: chatactoe.py

libraries:
- name: django
  version: "1.4"
