# uncomment below and replace with your Project ID
# application: YOUR_PROJECT_ID
module: tictactoe
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: chatactoe.app
  #script: chatactoe.py

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
