runtime: python27
threadsafe: true
api_version: 1

handlers:
# The endpoints handler must be mapped to /_ah/api.
- url: /_ah/api/.*
  script: main.api

libraries:
- name: pycrypto
  version: 2.6

# Endpoints 1.1 uses background threads for caching and reporting to service
# management and service control.
manual_scaling:
  instances: 1

beta_settings:
  use_endpoints_api_management: true
  endpoints_swagger_spec_file: echo-v1_swagger.json

env_variables:
  #TODO: The Endpoints service name.
  ENDPOINTS_SERVICE_NAME: {your-service.appspot.com}
  #TODO: The version Id of the uploaded Endpoints service.
  ENDPOINTS_SERVICE_VERSION: {2016-08-01r01}
